### DISCUSSION TITLE
Chroma syntax highlighting

### DISCUSSION THREAD

**Discussion by ghost** [thuliteio/doks#1008] [Q&A] [answered]
Hey,

I tried following [documentation](https://getdoks.org/docs/how-to/common-features/highlight-js/). I am trying to use Chroma highlighting as current highlighting is lacking a bit. For example in C# code the attributes in [ ] are considered meta.

When doing `highLight = false` in `./config/_default/params.toml` as said in documentation I lose code syntaxing completely.
I use \`\`\`csharp myCode \`\`\` for code snippets as that's how my API is generated.
Additionaly, I have edited highlight.js and added csharp as a language.

Example of code snippet:
```csharp
[Platform(1)]
public void TestCase_1()
{
    const double defaultValue = 4.0;

    // Execute something
    // More code
}
```

And this is how it looks, I wish to edit the result.
![image](https://user-images.githubusercontent.com/49745287/218468594-3e3ae1f4-d91e-4a88-b02d-73f6c52ee4ec.png)

**Comment by h-enk** [comment, marked as answer]
Did you set `codeFences = true` in [`markup.toml`](https://github.com/h-enk/doks/blob/master/config/_default/markup.toml#L15-L24)?

These settings work for me:

```toml
[highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false
  noHl = false
  style = 'github-dark'
  tabWidth = 4
```
