### DISCUSSION TITLE
toggle syntax highlighting when dark/light theme button toggled

### DISCUSSION THREAD

**Discussion by salmanhk** [thuliteio/doks#108] [Q&A] [answered]
Is there a way to toggle between syntax highlighting when the theme dark/light button is toggled? For example, you could generate two css files and use the correct one.
hugo gen chromastyles --style=monokai > syntax_darkmode.css
hugo gen chromastyles --style=vs > syntax_lightmode.css

Code seems to become unreadable otherwise.

This:
![syntax_ok](https://user-images.githubusercontent.com/31168522/106831711-01e5f380-6656-11eb-9c3e-10f367af7975.png)
becomes this:
![syntax_problem](https://user-images.githubusercontent.com/31168522/106831498-a582d400-6655-11eb-904a-252100c7bf16.png)

I have uncommented line 17 of the app.scss file and generated the chromastyle css in \static\css\.

Thanks.

**Comment by kevinrpb** [comment, marked as answer]
Hi there! There is an easy way of doing this. In you `syntax_darkmode.scss`, you can enclose everything with a `body.dark` selector. That way when the body changes the class that enables dark mode your code highlighting will also change. E.g.:

```scss
// syntax_lightmode.scss

/* Background */ .chroma { background-color: #f8f8f8 }
/* LineTableTD */ .chroma .lntd { vertical-align: top; padding: 0; margin: 0; border: 0; }
/* ... */
```

```scss
// syntax_darkmode.scss

body.dark {
  /* Background */ .chroma { color: #f8f8f2; background-color: #282a36 }
  /* LineTableTD */ .chroma .lntd { vertical-align: top; padding: 0; margin: 0; border: 0; }
}
/* ... */
```

Beware that you might need to tweak other things in dark mode such as the default `code` background to match the theme. In my case I could do this with:

```scss
// syntax_darkmode.scss

body.dark .chroma code { background: none; }
/* ... */
```
