### DISCUSSION TITLE
Using images in docs

### DISCUSSION THREAD

**Discussion by Orilcious** [thuliteio/doks#1100] [Q&A]
Hello,

This is what my docs structure currently looks like:

```
hyas-project/content/docs$ find
.
./faq
./faq/sicherheit.md
./faq/wer-seid-ihr.md
./faq/_index.md
./faq/finanzen.md
./_index.md
./dienstleistungen
./dienstleistungen/Kanboard.png
./dienstleistungen/inhalte-veroeffentlichen.md
./dienstleistungen/hosten.md
./dienstleistungen/_index.md
./dienstleistungen/lernen.md
./dienstleistungen/kommunizieren.md
./dienstleistungen/projekte-umsetzen.md
```

When I try to add an image to a post like this
```
---
title: "Projekte Umsetzen"
description: ""
summary: ""
date: 2023-09-19T16:16:16+02:00
lastmod: 2023-09-19T16:16:16+02:00
images: []
menu:
  docs:
    parent: "Dienstleistungen"
    identifier: "projekte-umsetzen-7ba90056ec711a9d51f090628ba48cb3"
weight: 999
toc: true
---

![image](Kanboard.png)

In unserem [Kanboard](https://kb.kabelsalat.it) werden Änderungen (Changes) dokumentiert.

Kanboard ist eine webbasierte Projektplanungssoftware, mit der Ihr Projekte in Teilaufgaben zerlegen könnt. Diese Teilaufgaben werden Karten genannt. Jeder aus eurem Team kann die Karten des Projekts einsehen und an ihnen arbeiten.

```

I get this error
```
Page resource image /docs/dienstleistungen/projekte-umsetzen/Kanboard.png not found
```

The error message suggests the image is expected to be at /docs/ and not at /content/docs/

Or am I doing something else wrong?

Kind regards,
Ori
