### DISCUSSION TITLE
How to make the navigation bar solid instead of transparent?

### DISCUSSION THREAD

**Discussion by compscibro** [thuliteio/doks#1101] [Q&A]
Hi, I am using the doks starter theme and it seems like the navbar is transparent, guessing that the opacity is around 70-80%. How can I make the navbar solid or in another word, how can I make the navbar non-transparent? I would appreciate if you could provide a detailed answer. Thanks!

**Comment by h-enk** [comment]
Sorry for the late reply. I guess you probably figured this one out yourself — by now. 

Add custom styles  — in `themes/my-doks-theme/assets/scss/common/_custom.scss` — overriding

```scss
.navbar {
    z-index: 1000;
    background-color: rgba(255,255,255,0.95);
    border-bottom: 1px solid #e9ecef;
}

[data-bs-theme="dark"] .navbar {
    background-color: rgba(23,24,28,0.95);
    border-bottom: 1px solid #23262f;
}
```
