### DISCUSSION TITLE
How to add multiple sections of blogs? (Personal + Tech)

### DISCUSSION THREAD

**Discussion by Rancho-rachit** [thuliteio/doks#1108] [Q&A] [answered]
I want to add another blog section (Tech Blogs). Which should work same as blog.

I tried - 
`npm run create -- --kind blog2 arch`

didn't work. 
following discussion, but it's for docs. - https://github.com/gethyas/doks/discussions/938

**Comment by h-enk** [comment, marked as answer]
Correct. There's no scaffold in place for `blog`,  like there is for `docs`. So then it comes down to:

1. Create the branch bundle index page:

    ```md
    npm run create tech-blog/_index.md
    ```

2. Create a leaf bundle page like so:

    ```md
     npm run create -- --kind blog tech-blog/my-tech-post/index.md
    ```

Make sure to set `draft: false` and add `type: blog` in the frontmatter of the pages.

Do you really want a separate blog-like section? You could also use categories and tags.

**Reply by Rancho-rachit** [reply]
Yes, I want a separate blog-like section.
Thanks👍

**Reply by technosprout** [reply]
Hi There:
I previously changed blog --> articles and docs-->guides; is this not possible with the new update?

**Comment by h-enk** [comment]
You would also need some custom css to mimic the blog section:

```css
.tech-blog.list .card, .tech-blog.single .card {
  margin-top: 2rem;
  margin-bottom: 2rem;
  transition: transform 0.3s;
}

.tech-blog.list .content .card:hover,
.tech-blog.single .content .card:hover {
  transform: scale(1.025);
}

.tech-blog.list .content .card-body,
.tech-blog.single .content .card-body {
  padding: 0 2rem 1rem;
}
```
