### DISCUSSION TITLE
Images being cropped and showing artifacts in content

### DISCUSSION THREAD

**Discussion by domdoescode** [thuliteio/doks#1125] [Q&A]
I'm using Markdown to add an image to page content, however it seems to be cropped and lowered in quality. I can see that Doks is using [gethyas/images](https://github.com/gethyas/images), but the link to the [How to Use docs](https://images.gethyas.com/) is broken :grimacing: 

Looking at the [Prometheus Operator](https://prometheus-operator.dev/docs/user-guides/getting-started/#installing-the-operator) site in the showcase I can see images rendering in the way that I'd expect (resizing with content, not cropped, quality remaining high), but can't find anywhere to explain how to change the system to provide that.

Example from the Prometheus Operator site:
![image](https://github.com/gethyas/doks/assets/524482/758d60e0-aca4-4604-b1a0-9648ebbb5630)

Example from a fresh local install of Doks, with the exact same image:
![image](https://github.com/gethyas/doks/assets/524482/381ec115-5bb5-4dae-981c-9a52fb00e704)

This is just using:
```
![Prometheus Operator Architecture](architecture.png)
```

Any help or advice would be appreciated :pray:

**Comment by h-enk** [comment]
It's a Hugo imaging configuration setting — see also [Processing options](https://gohugo.io/content-management/image-processing/#processing-options)

When you set [Anchor](https://gohugo.io/content-management/image-processing/#anchor) to "Center" — instead of the default value  "Smart" —  you should be fine.

Set in `config/_default/hugo.toml`:

```toml
[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 75
  resampleFilter = "Box"
```

I will add this to the Hyas/Doks documentation

**Reply by matben1611** [reply]
changing the "anchor" doesnt seem to change anything for me. Is there any other way to solve this exact same issue?

**Comment by h-enk** [comment]
> but the link to the [How to Use docs](https://images.gethyas.com/) is broken

Working on this right now 😉 — available soon

**Comment by h-enk** [comment]
I recommend these settings for [`quality`](https://gohugo.io/content-management/image-processing/#quality) and [`resampleFilter`](https://gohugo.io/content-management/image-processing/#resampling-filter)

```toml
[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"
```
