### DISCUSSION TITLE
How to override config values?

### DISCUSSION THREAD

**Discussion by ismailsimsek** [thuliteio/doks#1137] [Q&A]
Thank you for the great theme/website 

What is the correct way to override  config values? without touching the default ones `config/_default/**.toml`? i dont want to change default files in order to keep it clean for future upgrades. like upgrading from doks 1.1.1 to 1.2.1 etc.

Tested many options to override following footer config but its not working! Tested it by replicating default config under following dirs but none works

- config/_default/hyas/****.toml
- config/dev/hyas/****.toml
- config/production/hyas/****.toml

```toml
# the config values i want to edit
[[footer]]
name = "Privacy Policy"

# or this one 

[en]
  [en.params]
    footer = 'Brought to you by <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
```
