### DISCUSSION TITLE
Docs with three level structure trouble...

### DISCUSSION THREAD

**Discussion by cnichte** [thuliteio/doks#1148] [Q&A]
Hello everyone, after few weeks of hard work my old Website with Wordpress is gone, and replaced by Hyas - hooray :-) but i have some trouble with three level Menu Structure in docs. Somehow my structure seems broken.

You can use Breadcrumb and left Side Navigator to explore the content.

On Level 0 the entire structure is correctly listed, with all childs:

* https://carsten-nichte.de/docs/

However, it does not list anything at level 1, for example

* https://carsten-nichte.de/docs/art+photography/

but Level 2 looks good again:
* https://carsten-nichte.de/docs/art+photography/allgemein/

The menu on the left-hand side also closes after clicking on an Page-Bundle - instead of staying open, when you navigate on the Page-Bundles, which imho also suggests that something is wrong with the paths. Google analytics also complains that something is wrong.

The structure looks like so:

```
docs/_index.md
docs/level-1/_index.md
docs/level-1/level-2a/_index.md
docs/level-1/level-2a/content-1.md
docs/level-1/level-2a/content-2.md

docs/level-1/level-2b/_index.md
docs/level-1/level-2b/content-3.md
docs/level-1/level-2b/content-4.md
```

What has to be in the frontmatter of all the _index.md files ??? 

Now it looks so:

docs/_index.md
```
menu:
  docs:
    parent:  ""
    identifier: "level0-4e0d0e0f89f7decc11eaad4ae9193018"
```

docs/level-1/_index.md
```
menu:
  docs:
    parent:  ""
    identifier: "level1-4e0d0e0f89f7decc11eaad4ae9193018"
```

docs/level-1/level-2a/_index.md 
```
menu:
  docs:
    parent:  ""
    identifier: "level2a-4e0d0e0f89f7decc11eaad4ae9193018"
```

I tried also

docs/_index.md
```
menu:
  docs:
    parent:  ""
    identifier: "level0-4e0d0e0f89f7decc11eaad4ae9193018"
```

docs/level-1/_index.md
```
menu:
  docs:
    parent:  "level-1"
    identifier: "level1-4e0d0e0f89f7decc11eaad4ae9193018"
```

docs/level-1/level-2a/_index.md 
```
menu:
  docs:
    parent:  "level-2a"
    identifier: "level2a-4e0d0e0f89f7decc11eaad4ae9193018"
``` 

But that doesn't change the behavior.

Where am I making a mistake? I am grateful for any help.

Best regards - Carsten

---

Ps. I use a modified `docs/list.html template` to get the tree structure with:

```
       {{ if eq .CurrentSection .FirstSection }}

        <ul>
          {{ range .Sections.ByTitle }}
            <li>
              <a href="{{ .RelPermalink }}">{{ .Title }}</a>
              {{ partial "list-childs-recursive.html" . }}
            </li>
          {{ end }}
        </ul>

        {{ else }}

        <ul>
          {{ range .RegularPages }}
          <li>
            <a href="{{ .RelPermalink }}">{{ .Title | markdownify }}</a>
          </li>
          {{ end }}
        </ul>

      {{ end }}
```

and the following `list-childs-recursive.html` partial

```
{{ $child_pages := union .Sections .Pages }}
<ul>
  {{ range $child_pages.ByTitle }}
  <li>
    <a href="{{ .RelPermalink }}"> {{ .Title }} </a>
    {{ if or (.Sections) (.Pages) }}
    {{ partial "list-childs-recursive.html" . }}
    {{ end }}
  </li>
  {{ end }}
</ul>
```
