### DISCUSSION TITLE
Where can I change the color of menu hover?

### DISCUSSION THREAD

**Discussion by heihahehe** [thuliteio/doks#1160] [Q&A]
I like this theme very much, I am working on customization, I want to change the color of the menu.
![daoh](https://github.com/gethyas/doks/assets/152707762/8492959f-62d0-4bbb-8b44-ff9e51949151)

**Comment by bora-7** [comment]
@h-enk bump

**Comment by h-enk** [comment]
In `assets/scss/common/_variables-custom.scss` — for example:

```scss
// Put your custom SCSS variables here

// Light mode
$primary: blue;

// Dark mode
$link-color-dark: aquamarine;
$button-color-dark: aquamarine;

:root,
::backdrop {
  --sl-color-accent-high: aquamarine;
}
```

Reference:
- `node_modules/@hyas/doks-core/assets/scss/common/_variables-overrides.scss`
- `node_modules/@hyas/doks-core/assets/scss/common/_colors.scss`
- `node_modules/bootstrap/scss/_variables.scss`
- `node_modules/bootstrap/scss/_variables-dark.scss`

**Reply by bora-7** [reply]
Thanks for your response, similarly how can I change the **font** of the theme?

**Reply by h-enk** [reply]
If you'd like to use system default fonts, add  to `assets/scss/common/_variables-custom.scss`:

```scss
// $font-family-sans-serif:      "Jost", system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
$font-family-sans-serif:      system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

If you'd like to use a Google font, the preferred way to do this (for performance reasons) is to localize the font with the help of a tool like for example [google-webfonts-helper](https://gwfh.mranftl.com/fonts)

For example:
- Select Monserrat, charset latin, style regular and 500
- Copy CSS for modern browsers (use folder prefix `/fonts/montserrat/`) and paste in `assets/scss/common/custom.scss`:

  ```scss
  // Put your custom SCSS code here
  
  /* montserrat-regular - latin */
  @font-face {
    font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
    font-family: 'Montserrat';
    font-style: normal;
    font-weight: 400;
    src: url('/fonts/montserrat/montserrat-v26-latin-regular.woff2') format('woff2'); /* Chrome 36+, Opera 23+, Firefox 39+, Safari 12+, iOS 10+ */
  }
  /* montserrat-500 - latin */
  @font-face {
    font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
    font-family: 'Montserrat';
    font-style: normal;
    font-weight: 500;
    src: url('/fonts/montserrat/montserrat-v26-latin-500.woff2') format('woff2'); /* Chrome 36+, Opera 23+, Firefox 39+, Safari 12+, iOS 10+ */
  }
  ```

- Download files, extract, and paste fonts in `/static/fonts/montserrat/`
- Add  to `assets/scss/common/_variables-custom.scss`:

```scss
// $font-family-sans-serif:      "Jost", system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
$font-family-sans-serif:      "Montserrat", system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";

```

And, voilà:

![Snag_690f560](https://github.com/gethyas/doks/assets/3902872/da1a9dba-18c1-4cb1-9922-50dce61f189d)


Reference:

- `node_modules/@hyas/doks-core/assets/scss/common/_variables-overrides.scss`
