### DISCUSSION TITLE
Theme Styles Broken After Update: GitHub Actions Deploy

### DISCUSSION THREAD

**Discussion by jonathanwalker** [thuliteio/doks#1182] [Q&A] [answered]
First of all thanks for maintaining such a wonderful theme and using it happily for a couple years now! Thanks for the great work you do. 

Theme works wonderfully during `npm run dev` and `npm run build` when ran locally. Moment I deploy through GitHub actions the sites styling seems to break. A local `npm run build` and uploading to s3 works just fine. I have tried just about everything and 
could use some troubleshooting steps if you have any ideas! 

- Ensured the baseurl is set to `https://example.com/` in `config/_default/hugo.toml`
- Tried adding baseurl to `config/production/hugo.toml`
- Tried adding baseurl to `config/next/hugo.toml`
- Browsed all other discussions
- Checked browser console with no obvious errors
- Tried rebuilding the site from a clean install
- Tweaked the existing example for github actions

Similar to this discussion issue: https://github.com/gethyas/doks/discussions/265

```yaml
name: Deploy Static Site
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME: ${{ secrets.BUCKET }}
  ROLE_ARN:    ${{ secrets.ROLE_ARN }}
  CF_DISTRO:   ${{ secrets.CF_ID }}
  AWS_REGION:  "us-east-1"
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ghactions
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'
      - name: Install dependencies
        run: npm install
      - name: Build production website
        run: npm run build
      - name: Sync static site
        run: |
          cd public/
          aws s3 sync . s3://${{ env.BUCKET_NAME }}/ --delete
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRO }} --paths "/*"
```
