### DISCUSSION TITLE
Implementing Contextual Documentation Menus for Versioned Documentation

### DISCUSSION THREAD

**Discussion by ngallo** [thuliteio/doks#1193] [Q&A]
I need assistance with enabling versioning on my GitHub documentation. I've managed to activate it by setting docsVersioning = true in the params.toml file.

However, when navigating to the documentation at docs/2.0/, the correct version is displayed, but the left-side menu still shows all versions (1.0, 2.0, etc.). How can I configure it to display only the content relevant to the current version based on the URL?

Having all versions listed in the side menu is confusing for users and I'd like to streamline it to only show the content corresponding to the version being viewed.

**Comment by h-enk** [comment]
Unfortunately, folder-based versioning is currently not supported. However, technically* it will be supported with the [updated section navigation](https://github.com/gethyas/doks-core/pull/92) — available soon! See also the example below.

*Technically it will work, but I'd like to make things a bit simpler and easier, update the UX — and support both folder-based and subdomain-based versioning. Will be part of the then next release

Then, put your versioned documentation directly under `content` (not `content/docs`) — for example:

```bash
content
├───docs
│   ├───guides
│   └───reference
├───main
│   ├───guides
│   └───reference
└───v1-12
    ├───guides
    └───reference
```

Customize URL's in `config/_default/hugo.toml` — for example:

```toml
[permalinks]
  [permalinks.page]
    main = "/docs/:sections/:slug/"
    v1-12 = "/docs/v1.12/:sections[1:]/:slug/"
  [permalinks.section]
    main = "/docs/:sections/"
    v1-12 = "/docs/v1.12/:sections[1:]/"
```

Older version:

![Snag_bdeb4b1](https://github.com/gethyas/doks/assets/3902872/c4c0b991-1ad6-4d84-927b-8d5c84324f10)

Latest version:

![Snag_bde401d](https://github.com/gethyas/doks/assets/3902872/c3c94ceb-649e-4509-975c-b80d85749429)

Latest development version

![Snag_bdef18b](https://github.com/gethyas/doks/assets/3902872/e54bb90a-67d8-4d54-8a20-f98e0445eee5)
