### DISCUSSION TITLE
Frontmatter for menu

### DISCUSSION THREAD

**Discussion by huntsyea** [thuliteio/doks#1204] [General]
I have been adding new folders in a section and noticed that in the original docs folder directory this code exists in frontmatter:

```
menu:
  docs:
    parent: ""
    identifier: "docs-9602b15bad02600f3883f55e2ade6b81
```

    

Should I be adding this?
