### DISCUSSION TITLE
How should I add TOC in my Blog page?

### DISCUSSION THREAD

**Discussion by siyehua** [thuliteio/doks#1206] [Q&A] [answered]
I have add `toc: true` in the page config, but it does't work.

```
---
title: "Example Post"
description: "Just an example post."
summary: "You can use blog posts for announcing product updates and features."
date: 2023-09-07T16:27:22+02:00
lastmod: 2023-09-07T16:27:22+02:00
draft: false
weight: 300
categories: []
tags: []
contributors: []
pinned: false
homepage: false
top: true
seo:
  title: "" # custom title (optional)
  description: "" # custom description (recommended)
  canonical: "" # custom canonical URL (optional)
  noindex: false # false (default) or true
---

Well-thought-through product announcements will help increase feature awareness and engage users with new functionality. Just like [sharing your public roadmap](https://canny.io/blog/should-you-have-a-public-roadmap/), it's also a great way to let potential customers see that you're constantly improving.

## Further reading

- Read [How to announce product updates and features](https://canny.io/blog/announce-product-updates-features/)
## Further reading2

- Read [How to announce product updates and features](https://canny.io/blog/announce-product-updates-features/)

```

<img width="1089" alt="image" src="https://github.com/gethyas/doks/assets/9376247/3f530a24-cb35-463e-8dce-83c9c48a793c">
