### DISCUSSION TITLE
Toggling the sidebar in the docs page.

### DISCUSSION THREAD

**Discussion by amirfarzamnia** [thuliteio/doks#1208] [Q&A] [answered]
Hyas Doks is performing well, yet it would be fantastic if we could toggle the sidebar on docs pages, like the one found here: https://doks.netlify.app/docs/guides/example-guide/.

Is there a method to achieve this?

**Comment by h-enk** [comment, marked as answer]
That's not an easy one (I guess you mean something like this: https://nextra.site/docs) — probably a solution using Bootstrap's [Collapse](https://getbootstrap.com/docs/5.3/components/collapse/) plugin

You would have to copy `node_modules/@hyas/doks-core/layouts/_default/single.html` and paste as `layouts/_default/single.html` (and make changes there)

BTW If you'd like to have more space, you could also set in `params.toml`:

```toml
# Doks (@hyas/doks-core)
[doks]
  # Navbar
  containerBreakpoint = "fluid" # "", "sm", "md", "lg" (default), "xl", "xxl", or "fluid"
```
