### DISCUSSION TITLE
Additional menu items

### DISCUSSION THREAD

**Discussion by teamcrisis** [thuliteio/doks#124] [Q&A]
Does anyone know of a way to:

1. Add the same page to the menu twice. Something like:
```
menu: 
  docs:
    parent: "prologue"
  docs:
    parent: "help"
```

2. Add an external link to the menu. For example, under the `help` parent.
