### DISCUSSION TITLE
Rename blog to posts

### DISCUSSION THREAD

**Discussion by satrox28** [thuliteio/doks#1270] [Q&A]
Hi, I am looking to rename the path blog to posts. 

Can you help me. @h-enk

**Comment by h-enk** [comment]
Update `config/_default/hugo.toml` with something like:

```toml
[permalinks]
  # blog = "/blog/:slug/"
  docs = "/docs/:sections[1:]/:slug/"
# docs = "/docs/1.0/:sections[1:]/:slug/"
  [permalinks.page]
    blog = "/posts/:slug/"
  [permalinks.section]
    blog = '/posts/'
```

See for more background: [Permalinks](https://gohugo.io/content-management/urls/#permalinks)
