### DISCUSSION TITLE
Adding an image to a blog post

### DISCUSSION THREAD

**Discussion by teresalves** [thuliteio/doks#1289] [Q&A]
Hi everyone! :)

I wanted an image for the blogpost header like it is being done here
https://getdoks.org/blog/

this is my example.md
```
---
title: "ex"
description: "hello"
summary: ""
date: 2024-08-22T16:27:22+02:00
lastmod: 2023-09-07T16:27:22+02:00
draft: false
images: ["/about-me/about-me/ellie2.png"]
weight: 9999
categories: []
tags: []
contributors: []
pinned: false
homepage: false
seo:
  title: "" # custom title (optional)
  description: "" # custom description (recommended)
  canonical: "" # custom canonical URL (optional)
  noindex: false # false (default) or true
---

Hey there
<p align="center">
  <img src=/about-me/about-me/ellie2.png width=300 height=500/>
</p>
```

The image in the text shows up, but no header. Just this:
<img width="734" alt="image" src="https://github.com/user-attachments/assets/2e20a19c-2900-4cd9-8325-0e878d0b95a0">

Should be a simple one but I don't get it. Any thoughts?

I also wanted to do something like what this example in your "Showcase" section has: 
https://foreverliketh.is/blog/. -with:
1- multiple posts per row
2- a top summary of the subjects so you can click the category you want to see
This part might be more complex so I can also leave it to another discussion

Thanks a bunch!
