### DISCUSSION TITLE
Make css style dependent of dark mode

### DISCUSSION THREAD

**Discussion by papanito** [thuliteio/doks#1297] [Q&A] [answered]
I have some custom css which is different for the dark mode. How do I activate them when switching to dark theme. In pervious version of the theme I had something like

```css
[data-dark-mode] body {
  background: $body-bg-dark;
  color: $body-color-dark;
}

[data-dark-mode] body a {
  color: $link-color-dark;
}
```

**Comment by h-enk** [comment, marked as answer]
Use the Bootstrap Sass mixin `color-mode()`. For example:

```scss
// Put your custom SCSS code here
h1 {
  background-color: yellow;
}

@include color-mode(dark) {
  h1 {
    background-color: lime;
  }
}
```

See also the Boostrap docs: [Building with Sass](https://getbootstrap.com/docs/5.3/customize/color-modes/#building-with-sass)
