### DISCUSSION TITLE
ERROR deprecated: .Site.LastChange was deprecated

### DISCUSSION THREAD

**Discussion by papanito** [thuliteio/doks#1298] [Q&A] [answered]
I currently cannot build the page in gitlab as it fails with

```
ERROR deprecated: .Site.LastChange was deprecated in Hugo v0.123.0 and will be removed in Hugo 0.136.0. Use .Site.Lastmod instead.
```
My pipeline looks as follows:

```yaml

image: node:latest

variables:
  HUGO_ENV: production
  LC_ALL: C.UTF-8
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - npm install
  - npm install hugo-bin --save-dev

test:
  stage: test
  script:
  - ./node_modules/hugo-bin/vendor/hugo  --environment staging
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
  - ./node_modules/hugo-bin/vendor/hugo  --environment production
  artifacts:
    paths:
      - public
  only:
    - master
``` 

I probably could user ` ignoreLogs`  in the hugo config, but not sure how exactly.
