### DISCUSSION TITLE
How to get thumbnails to disply properly on `/blog` page

### DISCUSSION THREAD

**Discussion by pokwir** [thuliteio/doks#1328] [Q&A] [answered]
Is there a way to get thumbnails to display properly on the /blog page? 
Not sure why mine is stretched, I am using the page bundle

![image](https://github.com/user-attachments/assets/fc719e6f-947b-4e16-beb9-3a543869597c)

![image](https://github.com/user-attachments/assets/5d84453b-f31a-4a07-abdc-fef7b1ea54a5)

Thanks!

**Comment by h-enk** [comment, marked as answer]
The `img-fluid` class got droppped out. I will readd it in the upcoming version of `@thulite/doks-core`.

For now, add to `assets/scss/common/_custom.scss`:

```scss
// Put your custom SCSS code here
img {
  max-width: 100%;
  height: auto;
}
```
