### DISCUSSION TITLE
Created multiple menus, locally they are working but they are giving 404 page not found error on server

### DISCUSSION THREAD

**Discussion by shubhamtrigyn** [thuliteio/doks#1345] [Q&A]
I have created multiple menus in Hugo doks theme they are working fine in local but only one link is working on ubuntu server rest are giving 404 page not found error. Any solution for that ?

**Comment by h-enk** [comment]
Your repo?

**Comment by h-enk** [comment]
In `config/production/hugo.toml` did you set `baseurl`?

**Comment by h-enk** [comment]
Did you use `url` in stead of `pageRef`? It should be the latter for internal page links.

For example like so:

```toml
[[main]]
  name = "Thulite"
  pageRef = "/thulite/"
  weight = 10
```
