### DISCUSSION TITLE
confused Chinese user here

### DISCUSSION THREAD

**Discussion by nfway** [thuliteio/doks#188] [General]
Greetings!

Doks is the reason that I want transfer from hexo to hugo.

1. I fork getdoks.org repo here : https://github.com/nfway/library , wanna clone it into my site (coz it's great)
2. I deploy to vercel, which is easy
3. I follow this [thread](https://github.com/h-enk/doks/discussions/173)  , to build a directory and sub-directory,  and try to make them appear in side-bar (left), well , it didn't go well. 

Problem :

 - [https://doks-fine.vercel.app/common/](https://doks-fine.vercel.app/common/) ,  I create this directory and doing what as the guide told, add menu and files 
 - it just not working....

Sorry for those stupid question coz I'm obviously not a coder, and besides, seems I'm the only one who use doks in Chinese, can't find more peers. 

Thanks the great job on this theme.

**Comment by epogrebnyak** [comment]
Making somehting work ina forign language is always a challenge, let's try to make ti work.

It seems you have acheved a lot at https://doks-fine.vercel.app/common/ (there is new text is Chinese)

What is a specific result that you wanted and it did not work?

**Reply by nfway** [reply]
Thanks for reply, here is what I want :

[开始使用]  (#/common/index.md)  `#the file should refer to : /common/index.md`

愿景
```
[如何确立] (#/common/vision/built-vision.md)  
[自我评估](#/common/vision/...) 
```
罗克奇价值表
领导者挑选
创新与变革

built-vision.md:

```
---
title: "愿景与使命"
description: "公益基金会管理资料库"
lead: "公益基金会管理资料库"
date: 2020-10-13T15:21:01+02:00
lastmod: 2020-10-13T15:21:01+02:00
draft: false
images: []
menu: 
  common:
    parent: "vision"
weight: 10
toc: true
---
```

**in menus.toml**: 

```
[[common]]
  name = "使用说明"
  weight = 1
  identifier = "about-lib"
  url = "/common/"

[[common]]
  name = "愿景使命"
  weight = 2
  identifier = "vision"
  url = "/common/vision/"

```
