### DISCUSSION TITLE
The styles of tables in markdown are not effect after deployment

### DISCUSSION THREAD

**Discussion by koktlzz** [thuliteio/doks#202] [Q&A] [answered]
I love doks and have been using it for nearly a month .But i met an issue which i don't know how to solve them :
I add these configuration in `_global.scss`:

```scss
th,
td {
  border: 1px solid #dcdcdc;
  font-size: 16px;
}

th {
  background-color: #ffc0cb;
}

td {
  background-color: #fff0f5;
}
```

And it works in local debugging:

![askdhsk](https://cdn.jsdelivr.net/gh/koktlzz/ImgBed@master/askdhsk.png)

But after i deploy my project on github, the tables' styles are none:

![20210331210826](https://cdn.jsdelivr.net/gh/koktlzz/ImgBed@master/20210331210826.png)

Thanks.
