### DISCUSSION TITLE
How to remove the lines on the footer of the homepage?

### DISCUSSION THREAD

**Discussion by CLannadZSY** [thuliteio/doks#224] [Q&A] [answered]
I want to remove this style, what file do I need to modify?

![image](https://user-images.githubusercontent.com/38000492/113876207-16777100-97ea-11eb-9478-e56d7e7c67c3.png)

**Comment by h-enk** [comment, marked as answer]
See `./assets/scss/layouts/_footer.scss`:

```scss
.footer {
  border-top: 1px solid $gray-200;
  padding-top: 1.125rem;
  padding-bottom: 1.125rem;
}
```

If e.g. you do not want to show the line on the homepage, add after `.footer` something like:

```scss
.home .footer {
  border-top: 0;
}
```
Note, the html `body` element contains (a) page type specific class(es)
