### DISCUSSION TITLE
Table margin

### DISCUSSION THREAD

**Discussion by zcliu** [thuliteio/doks#356] [Q&A] [answered]
I'm adding some tables in my docs page. Here's an example:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1891340/123165527-5988ce00-d442-11eb-846f-4e285427c255.png">

There's a wide top margin for the table. How do I remove it? Thanks for this awesome theme!

**Comment by h-enk** [comment, marked as answer]
Hi @zcliu, update `./assets/scss/components/_tables.scss`. E.g. make it:

```scss
table {
  @extend .table;

  margin: 1rem 0 3rem;
}
```
