### DISCUSSION TITLE
Plotly Chart doesn't render. Shortcodes

### DISCUSSION THREAD

**Discussion by Alrodr** [thuliteio/doks#461] [Q&A] [answered]
Hello everyone,

I am trying to display a plot on one of my pages. Everything works for me on localhost, but not on the web. I have tried everything and I have searched a lot for documentation but I am not able to fix it.
Could someone help me?

I leave below all the code and schematics:

**layouts/shortcodes/plotly.html**
**layouts/shortcodes/load-plotly.html**
**layouts/partials/head/head.html**
**content/es/docs/y/x.md**
**static/global_map_counts.json**

Thank you very much!

CODE:
**layouts/shortcodes/plotly.html**
```
{{ $json := .Get "json" }}
{{ $height := .Get "height" | default "200px" }}
<div id="{{$json}}" class="plotly" style="height:{{$height}}"></div>
<script>
Plotly.d3.json({{$json}}, function(err, fig) {
    Plotly.plot('{{$json}}', fig.data, fig.layout, {responsive: true});
});
</script>
```
**layouts/shortcodes/load-plotly.html**
```
{{ if not ($.Page.Scratch.Get "plotlyloaded") }}
  {{ $.Page.Scratch.Set "plotlyloaded" 1 }}
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{{ end }}
```
**layouts/partials/head/head.html**
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {{ block "head/resource-hints" . }}{{ partial "head/resource-hints.html" . }}{{ end }}
  {{ block "head/script-header" . }}{{ partial "head/script-header.html" . }}{{ end }}
  {{ block "head/stylesheet" . }}{{ partial "head/stylesheet.html" . }}{{ end }}
  {{ block "head/seo" . }}{{ partial "head/seo.html" . }}{{ end }}
  {{ block "head/favicons" . }}{{ partial "head/favicons.html" . }}{{ end }}

 {{- if .Params.Plotly }}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{{- end }}
```

**content/es/docs/y/x.md**
```
---
title: "X"
description: "X"
lead: "x"
date: 2020-10-06T08:48:57+00:00
lastmod: 2020-10-06T08:48:57+00:00
draft: false
images: []
menu:
  docs:
    parent: "y"
weight: 10
toc: true
plotly: true
---

{{< load-plotly >}}
{{< plotly json="/global_map_counts.json" height="450px" >}}
```

**static/global_map_counts.json**
```
{
  "data": [
      {
          "x": [
              "giraffes",
              "orangutans",
              "monkeys"
          ],
          "y": [
              20,
              14,
              23
          ],
          "type": "bar"
      }
  ]
}
```
