### DISCUSSION TITLE
[doks 0.3.5 ] Mermaid background color in dark-mode

### DISCUSSION THREAD

**Discussion by OCram85** [thuliteio/doks#490] [Q&A] [answered]
I recently updated my doks based sites to version `0.3.5` and tried to set the background color again again for mermaid blocks:

In previous versions I set a static color for light and dark mode like this:

- `_mermaid.scss`  default for light mode 
```scss
.mermaid {
  ...
  ...
  background-color: rgba($lagoon-60, 0.5);
  border-color: $midnight-600;
  border-width: 1px;
  border-style: solid;
  border-radius: 5px;
}
```
The background was set globally here: 

![image](https://user-images.githubusercontent.com/13993700/136170874-be723205-6490-4bc4-89c4-bace6f10c50d.png)

So doks 0.3.5 now introduced the darkmode settings in `_dark.sccs`. I tried to migrate to the new schema with this:

```scss
[dark-dark-mode] body .mermaid {
  background-color: rgba($lagoon-40, 0.5);
}
```

Unfortunately this doesn't affect anything. The rule doesn't seem to match and won't be applied.

Do I use the wrong selector? Thanks for any help! 😄

**Comment by h-enk** [comment, marked as answer]
What about:

```scss
[data-dark-mode] body .mermaid {
  background-color: rgba($lagoon-40, 0.5);
}
```
