### DISCUSSION TITLE
docker-compose script

### DISCUSSION THREAD

**Discussion by ImaCrea** [thuliteio/doks#569] [How-to guides]
Sharing is caring.

Here's my yml for anyone wanting to run it in a docker container to work on their local environment.

```
version: "2"
services:
  node:
    image: "node:17"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports: 
      - 1313:1313 
    command: "npm start"
```

In short : 
- Create a docker-compose.yml file at the root of your doks folder and copy/paste this script inside.
- Run first in your terminal `docker-compose run node npm install` this will install the dependencies and all
- Then to run and deploy type `docker-compose up` and open your browser on `127.0.0.1:1313` to see your Doks live :)

Changes made are reloaded live on the browser. If no change happen, it's because there's an error while building the site, check your terminal and log ;)

(Of course, you need [Docker desktop](https://www.docker.com/products/docker-desktop) set up on your machine.)
