### DISCUSSION TITLE
I can't seem to get single level menu working?

### DISCUSSION THREAD

**Discussion by 4x4notfound** [thuliteio/doks#715] [Q&A]
Example:
https://getdoks.org/tutorial/add-menus/

My menu config:

```
  [[tutorial]]
    name = "Introduction"
    weight = 10
    identifier = "tutorial-introduction"
    url = "/tutorial/introduction/"
```

No left sidebar menu is generated for the page at that `url`. For 2 level nested menu works fine in another section.

**Comment by h-enk** [comment]
In `config\_default\menus.toml`, make it: 

```toml
[[tutorial]]
  name = "Tutorial"
  weight = 10
  identifier = "tutorial"
  url = "/tutorial/"
```

In `content\tutorial\introduction.md`, add:

```md
---
..
menu:
  tutorial:
    parent: "tutorial"
weight: 010
..
---
```

If that didn't work, please provide a repo
