### DISCUSSION TITLE
Docs Menu Sorting Broke

### DISCUSSION THREAD

**Discussion by CaiB** [thuliteio/doks#762] [Q&A] [answered]
Hello!

I'm trying to update my website from Doks 0.1.2 to the latest (0.4.3), however I'm encountering an issue with the docs pages left navigation sidebar. It appears to have lost its sorting after the update. I copied the content and menu.toml over directly, so I expected it'd keep that, but on the new version the sorting seems somewhat random, and is different in different languages (but it's not alphabetic).

E.g. from `config/_default/menus/menus.en.toml`:
```toml
[[docs]]
  name = "General"
  weight = 10
  identifier = "general"
  url = "/docs/general/"

[[docs]]
  name = "Sources"
  weight = 50
  identifier = "sources"
  url = "/docs/sources/"

[[docs]]
  name = "Controllers"
  weight = 90
  identifier = "controllers"
  url = "/docs/controllers/"

...
```

Result:
![image](https://user-images.githubusercontent.com/6701127/169629923-819bb17f-0a87-4aca-ac4f-e9b55f07b9d2.png)

I couldn't find any information on a new way to do this, did something change I need to adapt to?
