### DISCUSSION TITLE
why make image render so complicated?

### DISCUSSION THREAD

**Discussion by yusank** [thuliteio/doks#773] [Q&A] [answered]
why render a standard image  `![title](src)` render to a new image and It become blur after render . Also why define so many option in config and make this this so complex. 

```toml
# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500] # do I suppose to know those numbers stand for ?
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x" # what is means for
smallLimit = "300" # and why should i have to set this
```

I don't see any benefit of this render , just render it to like `<img src="src" class="center" width="100%">` or support the `image`  shortcut is quite simple and customizable for user.
