### DISCUSSION TITLE
How to press enter to complete line break directly？（markdown to HTML）

### DISCUSSION THREAD

**Discussion by zhaozhiliao** [thuliteio/doks#808] [Q&A] [answered]
According to the markdown specification, when wrapping a line, you need to enter two spaces first, and then press Enter.
How to set it, press the enter key to complete the line feed display directly.
thanks

**Comment by h-enk** [comment, marked as answer]
In `./config/_default/markup.toml` did you try by setting `hardWraps = true`, like so:

```toml
defaultMarkdownHandler = "goldmark"

[goldmark]
  [goldmark.extensions]
    linkify = false
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    [goldmark.parser.attribute]
      block = true
      title = true
  [goldmark.renderer]
    hardWraps = true
    unsafe = true
```

See also the Hugo docs: [Configure Markup](https://gohugo.io/getting-started/configuration-markup/#configure-markup)
