### DISCUSSION TITLE
Disable/enable toc sitewide

### DISCUSSION THREAD

**Discussion by pensivedog** [thuliteio/doks#821] [General]
Page frontmatter allows to disable the RHS table of contents with `toc: false`. Is there any way to set this on a site, rather than page, level?

**Comment by codeaphex** [comment]
You can use the Hugo Cascade function for something like this
<https://gohugo.io/content-management/front-matter/#front-matter-cascade>

```yaml
---
title: "Root _index.md"
draft: false
cascade:
  toc: false
---
```
