### DISCUSSION TITLE
Can the /docs/ part of the url be replaced with another word?

### DISCUSSION THREAD

**Discussion by genebean** [thuliteio/doks#882] [Q&A] [answered]
I am working on a site for an orginazation that fits nicely in the structure provided by Doks but I would like to rename the docs menu to info and have the url also have say info instead. For example, I'd like `http://localhost:1313/docs/prologue/introduction/` to instead show up as `http://localhost:1313/info/prologue/introduction/`. I am fine with the actual directory on disk still being called docs as I am only seeking a visual change for the users of the site.

**Comment by h-enk** [comment, marked as answer]
In `./config/_default/config.toml` add the permalink structure you'd like, e.g.:

```toml
[permalinks]
  blog = "/blog/:title/"
# docs = "/docs/1.0/:sections[1:]/:title/"
  docs = "/info/:title/"
```
