### DISCUSSION TITLE
Multi level menu

### DISCUSSION THREAD

**Discussion by mazwat** [thuliteio/doks#892] [General]
Hi,

I'm trying to build a menu with multiple nested layers. But I am struggling to implement it with sub folders and _index.md configurations. I am trying to create this:

<img width="204" alt="Screenshot 2022-09-07 at 18 48 16" src="https://user-images.githubusercontent.com/570587/188945097-30a3da03-f053-4350-8a50-2c26ed649ec4.png">

But I get this?

<img width="253" alt="Screenshot 2022-09-07 at 18 49 56" src="https://user-images.githubusercontent.com/570587/188945464-7b2cc2fa-1a30-443a-be40-079fe853acfc.png">

Is it not possible to have two or three levels of nesting? 

I figure it could be something to with some config elements. My markup.toml is like this:
```

[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
```

and my menus.en.toml is like this:
```

[[docs]]
  name = "Components"
  weight = 14
  identifier = "components"
  url = "/docs/components/"

[[docs]]
  name = "Help"
  weight = 15
  identifier = "help"
  url = "/docs/help/"

[[docs]]
  name = "Lab"
  weight = 16
  identifier = "lab"
  url = "/docs/lab/"

[[docs]]
  name = "Teaching"
  weight = 17
  identifier = "teaching"
  url = "/docs/teaching/"
```
Any thoughts would be much appreciated. Thanks.

**Comment by mazwat** [comment]
I apologise this was down to my own misunderstanding. I realized after downloading the main 'doks' repo and reproducing the _Lorem/Ipsum_ folder structure and using the frontmatter headers correctly I have resolved it:
```

---
title: "ROB210"
description: ""
lead: ""
date: 2022-01-18T20:00:32+01:00
lastmod: 2022-01-18T20:00:32+01:00
draft: false
images: []
menu:
  docs:
    parent: "teaching"
    identifier: "rob210"
weight: 999
toc: true
---
```
This may help another newbie :)
