### DISCUSSION TITLE
Netlify contact forms

### DISCUSSION THREAD

**Discussion by genebean** [thuliteio/doks#895] [Q&A] [answered]
Anyone have tips on how to make nice looking contact forms that hook into Netlify? I tried just copy/pasting my code from my old theme but it doesn’t look very good and the submit button is tiny.

**Comment by genebean** [comment, marked as answer]
Found my own problem: I had forgotten I was using i18n data in the form. My old form had this in in `i18n/en.toml`:

```toml
[repliestext]
  one = "Replies typically within 1 hour."
  other = "Replies typically within {{ .Count }} hours."
[submit]
  other = "Submit"
```

That translated to this in the Doks theme `i18n/en.yaml`:


```yaml
- id: repliestext
  translation:
    one: "Replies typically within 1 hour."
    other: "Replies typically within {{ .Count }} hours."

- id: submit
  translation:
    other: "Submit"
```
