### DISCUSSION TITLE
Change max menu sublevel count?

### DISCUSSION THREAD

**Discussion by codeaphex** [thuliteio/doks#980] [Q&A]
I have the following structure of my (test) docs
![image](https://user-images.githubusercontent.com/39407721/211224908-d7e9e23c-3fac-468a-b5bc-e61d7f93a44b.png)
So multiple subfolders with branch index files, and 2 final leaf branches (Resume and doks).
The menu is automatically generated up to the Hugo branch, but is showing the Themes branch as a link:
![image](https://user-images.githubusercontent.com/39407721/211224985-200b435c-38ac-4e8b-a843-178db1f9935c.png)

If I click on it, it shows the Leaf branches as child pages, but the menu is completly missing.
![image](https://user-images.githubusercontent.com/39407721/211225051-3c5c6e64-40cd-4d99-8350-521852baa98b.png)

This is the content of the themes/_index.md
```yaml
---
title: "Themes"
description: ""
lead: ""
date: 2023-01-08T18:36:57+01:00
lastmod: 2023-01-08T18:36:57+01:00
draft: false
images: []
menu:
  docs:
    parent: "hugo"
    identifier: "themes-d2a0fff51bd74ae05d1ca74d383e0959"
weight: 999
toc: true
---

```

Is this happening because there is some limit on the sublevels? Can this be modified?
