### ISSUE TITLE
Error: failed to resolve "docs" to an archetype template

### ISSUE THREAD

**Issue by Squadz** [thuliteio/doks#1318]
## Description
I'm getting the following error "**Error: failed to resolve "docs" to an archetype template**"

### Steps to reproduce
```npm create thulite@latest -- --template doks
cd .\doks\
npm install
npm run create -- --kind docs tutorials
```

### Expected result

Create another main section ? ([Navigation](https://getdoks.org/docs/basics/navigation))

### Actual result
**Error: failed to resolve "docs" to an archetype template**

### Environment
Windows / Powershell

**Comment by h-enk** [comment]
Did you add the new `tutorials` section to `config/_default/params.toml`:

```toml
# Doks (@thulite/doks-core)
[doks]
  # Nav
  sectionNav = ["docs", "tutorials"] # ["docs"] (default) or list of sections (e.g. ["docs", "guides"])
```

See also: [Other main sections](https://getdoks.org/docs/basics/navigation/#other-main-sections)

If you can share your repo, I can take a closer look
